# Generated by Django 2.1.5 on 2020-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201004_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idnum',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
