# Generated by Django 2.1.5 on 2020-10-04 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201004_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last activity'),
        ),
    ]
