# Generated by Django 2.1.5 on 2020-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='instances',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
