# Generated by Django 2.1.5 on 2020-10-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='instances',
            field=models.IntegerField(default=1),
        ),
    ]
