# Generated by Django 2.1.5 on 2020-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201004_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
