# Generated by Django 2.1.5 on 2020-10-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
