# Generated by Django 3.1.1 on 2020-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20201001_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='hi', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
